name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        # FTP server name (you may need to specify a port)
        FTP_SERVER: ta18aru.itmajakas.ee
        # FTP account username
        FTP_USERNAME: d82653f180951
        # FTP account password
        FTP_PASSWORD: ${{ secrets:FTP_PASSWORD }}
        # Protocol used to deploy (ftp or sftp)
        port: 21 # optional, default is 21
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        remote_dir: /kalku # optional, default is 

